/*
Project: Experimentation & Business Impact Analytics using SQL
File: revenue_impact.sql
Author: Sathvik
Purpose:
Measure the revenue impact of experiment variants by analyzing
total revenue, ARPU, and revenue uplift between variants.

Assumptions:
1. Revenue is generated only from successful payments
2. payment_status = 'success' indicates valid revenue
3. Each user belongs to only one experiment variant
*/

--------------------------------------------------
-- Business Question 1:
-- Which users are part of each experiment variant?
--------------------------------------------------

WITH experiment_users AS (
    SELECT DISTINCT
        user_id,
        variant
    FROM experiments
)
SELECT
    user_id,
    variant
FROM experiment_users
ORDER BY variant, user_id;

-- Explanation:
-- Establishes the experiment population.
-- Used as the base for all revenue impact calculations.

--------------------------------------------------
-- Business Question 2:
-- How much total revenue has each user generated?
--------------------------------------------------

WITH user_revenue AS (
    SELECT
        o.customer_id AS user_id,
        SUM(p.payment_value) AS revenue
    FROM orders o
    JOIN payments p
        ON o.order_id = p.order_id
    WHERE p.payment_status = 'success'
    GROUP BY o.customer_id
)
SELECT
    user_id,
    revenue
FROM user_revenue
ORDER BY revenue DESC;

-- Explanation:
-- Aggregates lifetime revenue per user.
-- Used to connect revenue outcomes to experiment variants.

--------------------------------------------------
-- Business Question 3:
-- How much total revenue is generated by each variant?
--------------------------------------------------

WITH experiment_users AS (
    SELECT DISTINCT
        user_id,
        variant
    FROM experiments
),
user_revenue AS (
    SELECT
        o.customer_id AS user_id,
        SUM(p.payment_value) AS revenue
    FROM orders o
    JOIN payments p
        ON o.order_id = p.order_id
    WHERE p.payment_status = 'success'
    GROUP BY o.customer_id
)
SELECT
    e.variant,
    ROUND(SUM(COALESCE(r.revenue, 0)), 2) AS total_revenue
FROM experiment_users e
LEFT JOIN user_revenue r
    ON e.user_id = r.user_id
GROUP BY e.variant
ORDER BY total_revenue DESC;

-- Explanation:
-- Measures overall revenue contribution of each variant.
-- Helps assess business impact beyond just conversion rate.

--------------------------------------------------
-- Business Question 4:
-- What is the Average Revenue Per User (ARPU) for each variant?
--------------------------------------------------

WITH experiment_users AS (
    SELECT DISTINCT
        user_id,
        variant
    FROM experiments
),
user_revenue AS (
    SELECT
        o.customer_id AS user_id,
        SUM(p.payment_value) AS revenue
    FROM orders o
    JOIN payments p
        ON o.order_id = p.order_id
    WHERE p.payment_status = 'success'
    GROUP BY o.customer_id
)
SELECT
    e.variant,
    COUNT(DISTINCT e.user_id) AS users,
    ROUND(
        SUM(COALESCE(r.revenue, 0)) /
        NULLIF(COUNT(DISTINCT e.user_id), 0),
        2
    ) AS arpu
FROM experiment_users e
LEFT JOIN user_revenue r
    ON e.user_id = r.user_id
GROUP BY e.variant
ORDER BY arpu DESC;

-- Explanation:
-- ARPU captures monetization quality per user.
-- A variant may have similar conversion but higher ARPU.

--------------------------------------------------
-- Business Question 5:
-- What is the ARPU uplift of Variant B compared to Variant A?
--------------------------------------------------

WITH variant_revenue AS (
    SELECT
        e.variant,
        SUM(COALESCE(p.payment_value, 0)) AS revenue,
        COUNT(DISTINCT e.user_id) AS users
    FROM experiments e
    LEFT JOIN orders o
        ON e.user_id = o.customer_id
    LEFT JOIN payments p
        ON o.order_id = p.order_id
       AND p.payment_status = 'success'
    GROUP BY e.variant
),
variant_arpu AS (
    SELECT
        variant,
        revenue * 1.0 / NULLIF(users, 0) AS arpu
    FROM variant_revenue
)
SELECT
    MAX(CASE WHEN variant = 'B' THEN arpu END)
    - MAX(CASE WHEN variant = 'A' THEN arpu END)
    AS absolute_arpu_lift,
    ROUND(
        (
            MAX(CASE WHEN variant = 'B' THEN arpu END)
            - MAX(CASE WHEN variant = 'A' THEN arpu END)
        ) /
        NULLIF(MAX(CASE WHEN variant = 'A' THEN arpu END), 0)
        * 100,
        2
    ) AS relative_arpu_lift_pct
FROM variant_arpu;

-- Explanation:
-- Quantifies monetization uplift of Variant B over Variant A.
-- This directly answers the question: "Did this experiment make more money?"
